import glob
import os
from astropy.io import fits

fits_file_names = \
    glob.glob("/Users/steveo/Documents/V3890_Sgr_Data/LT_Spectra/JL19A06private2105703012reduced/*.fits.gz")

print(f"# Code generated by {os.path.basename(__file__)}")
print("from typing import Dict")
print("import numpy as np")
print("\n")
print("def get_spectra_epochs(eruption_jd: float) -> Dict[str, float]:")
print("    \"\"\"")
print("    Gets the timing of the LT Spectra for the 2019 eruption as an epochs dictionary.")
print("    \"\"\"")
print("    offset = np.subtract(2400000, eruption_jd)")
print("    return {")
for fits_file_name in sorted(fits_file_names, key=os.path.getmtime):
    with fits.open(fits_file_name) as hdul:
        header = hdul["L1_IMAGE"].header
        print(f"        \"{header['DATE-OBS']}-{header['CONFNAME']}\": np.add({header['MJD']}, offset),")
print("    }")
