import glob
import os
from astropy.io import fits
from utility import timing as tm

fits_file_names = \
    glob.glob("/Users/steveo/Documents/V3890_Sgr_Data/LT_Spectra/JL19A06private2105703012reduced/?_e_2019????_*_1_1_2.fits.gz")

print(f"# Code generated by {os.path.basename(__file__)}")
print("from typing import Dict")
print("from utility import timing as tm")
print("\n")
print("def get_spectra_epochs(eruption_jd: float) -> Dict[str, float]:")
print("    \"\"\"")
print("    Gets the timing of the LT Spectra for the 2019 eruption as an epochs dictionary.")
print("    \"\"\"")
print("    return {")
for fits_file_name in sorted(fits_file_names, key=os.path.basename):
    with fits.open(fits_file_name) as hdul:
        header = hdul["L1_IMAGE"].header
        mjd = header["MJD"]
        base_name = os.path.basename(fits_file_name).replace("_1_1_2.fits.gz", "")
        print(f"        \"{base_name}\": tm.delta_t_from_jd({tm.jd_from_mjd(mjd)}, eruption_jd),")
print("    }")
